services:
  bot:
    pull_policy: always
    env_file:
      - ../env/stage.env
      - ../env/stage.secrets.env
    ports:
      - "127.0.0.1:9111:9101"
    labels:
      com.tea-party.environment: stage

  worker:
    pull_policy: always
    env_file:
      - ../env/stage.env
      - ../env/stage.secrets.env
    ports:
      - "127.0.0.1:9112:9102"
    labels:
      com.tea-party.environment: stage

  postgres:
    env_file:
      - ../env/stage.env
      - ../env/stage.secrets.env
    ports:
      - "127.0.0.1:5433:5432"
