services:
  bot:
    image: tea-party-reservation-bot:bot-local
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ./env/local.env

  worker:
    image: tea-party-reservation-bot:worker-local
    build:
      context: ../../
      dockerfile: Dockerfile
    env_file:
      - ./env/local.env

  postgres:
    env_file:
      - ./env/postgres.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
