services:
  bot:
    pull_policy: always
    env_file:
      - ../env/prod.env
      - ../env/prod.secrets.env
    ports:
      - "127.0.0.1:9101:9101"
    labels:
      com.tea-party.environment: prod

  worker:
    pull_policy: always
    env_file:
      - ../env/prod.env
      - ../env/prod.secrets.env
    ports:
      - "127.0.0.1:9102:9102"
    labels:
      com.tea-party.environment: prod

  postgres:
    env_file:
      - ../env/prod.env
      - ../env/prod.secrets.env
    ports:
      - "127.0.0.1:5432:5432"
